version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - flower-net

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    networks:
      - flower-net
    depends_on:
      - backend

networks:
  flower-net:
