name: CI-CD Flower Shop

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: flower-eks

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Get AWS Account ID
      id: aws-account
      run: echo "account_id=$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_ENV

    - name: Login to ECR
      run: |
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ env.account_id }}.dkr.ecr.$AWS_REGION.amazonaws.com

    - name: Build and push backend image
      run: |
        docker build -t flower-backend ./backend
        docker tag flower-backend:latest ${{ env.account_id }}.dkr.ecr.$AWS_REGION.amazonaws.com/flower-backend:latest
        docker push ${{ env.account_id }}.dkr.ecr.$AWS_REGION.amazonaws.com/flower-backend:latest

    - name: Build and push frontend image
      run: |
        docker build -t flower-frontend ./frontend
        docker tag flower-frontend:latest ${{ env.account_id }}.dkr.ecr.$AWS_REGION.amazonaws.com/flower-frontend:latest
        docker push ${{ env.account_id }}.dkr.ecr.$AWS_REGION.amazonaws.com/flower-frontend:latest

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

    - name: Set up Helm
      uses: azure/setup-helm@v3

    - name: Deploy backend chart
      run: |
        helm upgrade --install flower-backend ./helm/backend \
          --set image.repository=${{ env.account_id }}.dkr.ecr.$AWS_REGION.amazonaws.com/flower-backend \
          --set image.tag=latest

    - name: Deploy frontend chart
      run: |
        helm upgrade --install flower-frontend ./helm/frontend \
          --set image.repository=${{ env.account_id }}.dkr.ecr.$AWS_REGION.amazonaws.com/flower-frontend \
          --set image.tag=latest
